# =============================================================================
# build-ui-icon.ps1 -- regenerate ui/assets/iesa-opt-ui.ico from the rect logo
# =============================================================================
#
# Windows Explorer shows .bat files with a hardcoded system icon, so to give
# the "Start IESA-Opt UI" launcher a custom icon we ship a .lnk shortcut
# (`IESA-Opt UI.lnk` at the repo root, auto-generated by
# scripts/launcher/start-ui.ps1) that points at
# scripts/launcher/start-ui.bat with IconLocation set to
# ui/assets/iesa-opt-ui.ico.
# This script generates that .ico from the project's rect-shaped brand logo
# (docs/src/assets/iesa-opt-logo-rect.png), embedding multiple resolutions
# as PNGs inside the ICO container -- modern Windows (Vista+) accepts that
# and the file stays small (~50 kB) while looking sharp at every zoom level.
#
# Re-run this script whenever the source PNG changes.

$ErrorActionPreference = "Stop"

$RepoRoot   = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$SourcePng  = Join-Path $RepoRoot "docs\src\assets\iesa-opt-logo-rect.png"
$DestIco    = Join-Path $RepoRoot "ui\assets\iesa-opt-ui.ico"
$IconSizes  = @(16, 24, 32, 48, 64, 128, 256)

if (-not (Test-Path $SourcePng)) {
    throw "Source PNG not found: $SourcePng"
}

$destDir = Split-Path -Parent $DestIco
if (-not (Test-Path $destDir)) {
    New-Item -ItemType Directory -Path $destDir -Force | Out-Null
}

Add-Type -AssemblyName System.Drawing

function New-PngBytes {
    param([System.Drawing.Bitmap]$Bitmap)
    $ms = New-Object System.IO.MemoryStream
    try {
        $Bitmap.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
        return ,$ms.ToArray()
    } finally {
        $ms.Dispose()
    }
}

$src = [System.Drawing.Image]::FromFile($SourcePng)
try {
    Write-Host ("Source : {0} ({1}x{2})" -f $SourcePng, $src.Width, $src.Height)

    # Pad the (slightly non-square) source onto a transparent square canvas
    # so the icon renders consistently regardless of aspect ratio.
    $maxDim = [Math]::Max($src.Width, $src.Height)
    $square = New-Object System.Drawing.Bitmap $maxDim, $maxDim, ([System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $g = [System.Drawing.Graphics]::FromImage($square)
    try {
        $g.Clear([System.Drawing.Color]::Transparent)
        $g.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
        $g.PixelOffsetMode   = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
        $g.SmoothingMode     = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
        $offsetX = [int](($maxDim - $src.Width)  / 2)
        $offsetY = [int](($maxDim - $src.Height) / 2)
        $g.DrawImage($src, $offsetX, $offsetY, $src.Width, $src.Height)
    } finally {
        $g.Dispose()
    }

    # Render the padded square down to each requested icon size.
    $entries = New-Object System.Collections.Generic.List[object]
    foreach ($size in $IconSizes) {
        $bmp = New-Object System.Drawing.Bitmap $size, $size, ([System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        $gg = [System.Drawing.Graphics]::FromImage($bmp)
        try {
            $gg.Clear([System.Drawing.Color]::Transparent)
            $gg.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
            $gg.PixelOffsetMode   = [System.Drawing.Drawing2D.PixelOffsetMode]::HighQuality
            $gg.SmoothingMode     = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality
            $gg.DrawImage($square, 0, 0, $size, $size)
        } finally {
            $gg.Dispose()
        }
        $entries.Add([pscustomobject]@{ Size = $size; Bytes = New-PngBytes -Bitmap $bmp }) | Out-Null
        $bmp.Dispose()
    }
    $square.Dispose()

    # Write the ICO container: ICONDIR (6 bytes) + N * ICONDIRENTRY (16 bytes) + N PNG payloads.
    $fs = [System.IO.File]::Create($DestIco)
    $bw = New-Object System.IO.BinaryWriter $fs
    try {
        $bw.Write([UInt16]0)                  # reserved
        $bw.Write([UInt16]1)                  # type 1 = icon
        $bw.Write([UInt16]$entries.Count)     # number of images

        $offset = 6 + ($entries.Count * 16)
        foreach ($e in $entries) {
            # Width/Height of 0 means "256 or larger" in the ICO format.
            $wByte = if ($e.Size -ge 256) { [byte]0 } else { [byte]$e.Size }
            $hByte = if ($e.Size -ge 256) { [byte]0 } else { [byte]$e.Size }
            $bw.Write($wByte)
            $bw.Write($hByte)
            $bw.Write([byte]0)                 # color count (0 = no palette)
            $bw.Write([byte]0)                 # reserved
            $bw.Write([UInt16]1)               # color planes
            $bw.Write([UInt16]32)              # bits per pixel
            $bw.Write([UInt32]$e.Bytes.Length) # image data size
            $bw.Write([UInt32]$offset)         # image data offset
            $offset += $e.Bytes.Length
        }

        foreach ($e in $entries) {
            $bw.Write($e.Bytes)
        }
    } finally {
        $bw.Flush()
        $bw.Dispose()
        $fs.Dispose()
    }
} finally {
    $src.Dispose()
}

$sizeKb = [math]::Round((Get-Item $DestIco).Length / 1KB, 1)
Write-Host ("Wrote  : {0} ({1} KB, {2} resolutions: {3})" -f $DestIco, $sizeKb, $IconSizes.Count, ($IconSizes -join ', '))
